image: node:14

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master"'
  script:
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        S3_BUCKET: dev-dora-frontend-pamo
        CLOUDFRONT_DISTRIBUTION_ID: EB6D7ZKOXK1U2
    - if: '$CI_COMMIT_BRANCH == "master"'
      variables:
        S3_BUCKET: dora-frontend-pamo
        CLOUDFRONT_DISTRIBUTION_ID: E1EIJ0SDVT8YFZ
  script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip
    - pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws s3 sync build/ s3://$S3_BUCKET --delete --region $AWS_DEFAULT_REGION
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
